// ═══════════════════════════════════════════════════════════════════════
// PEPTIDE EDUCATIONAL DATA — Benefits, Mechanisms, Storage, Use Cases
// Keyed by peptide name. Merged into Peptide objects at build time.
// ═══════════════════════════════════════════════════════════════════════

export interface PeptideSourceRef {
  title: string;
  url: string;
}

export interface PeptideEducationalData {
  primaryBenefit: string;
  shortSummary: string;
  benefits: string;
  administrationMethod: string;
  administrationDetails: string;
  storage: string;
  mechanism: string;
  useCases: string[];
  stacks: string[];
  safetyNotes: string;
  researchBackground: string;
  relatedPeptideNames: string[];
}

export const PEPTIDE_EDUCATION: Record<string, PeptideEducationalData> = {
  "Semaglutide": {
    primaryBenefit: "Blood sugar regulation and weight management",
    shortSummary: "A GLP-1 receptor agonist used for type 2 diabetes and chronic weight management.",
    benefits: "Semaglutide improves glycemic control by stimulating insulin release and reducing glucagon secretion. It also slows gastric emptying and reduces appetite, leading to significant weight loss. Clinical trials have demonstrated cardiovascular risk reduction in patients with type 2 diabetes.",
    administrationMethod: "Subcutaneous Injection / Oral",
    administrationDetails: "Administered as a once-weekly subcutaneous injection (Ozempic/Wegovy) or as a daily oral tablet (Rybelsus). The oral form should be taken on an empty stomach with a small amount of water at least 30 minutes before food.",
    storage: "Store unused pens in a refrigerator at 2-8°C. After first use, pens may be kept at room temperature (up to 30°C) or refrigerated for up to 56 days. Do not freeze. Keep the pen cap on when not in use.",
    mechanism: "Semaglutide binds to and activates the GLP-1 receptor on pancreatic beta cells, enhancing glucose-dependent insulin secretion. It also suppresses glucagon release, slows gastric emptying, and acts on hypothalamic appetite centers to reduce food intake. Albumin binding via a C-18 fatty acid chain extends its half-life.",
    useCases: ["Metabolic Health", "Fat Loss", "Cardiovascular"],
    stacks: ["Tirzepatide (alternative dual-agonist approach)", "CagriSema (semaglutide + cagrilintide combination)"],
    safetyNotes: "Common side effects include nausea, vomiting, diarrhea, and constipation, particularly during dose escalation. There is a boxed warning regarding thyroid C-cell tumors observed in rodent studies. Contraindicated in patients with a personal or family history of medullary thyroid carcinoma.",
    researchBackground: "Developed by Novo Nordisk, semaglutide was approved for type 2 diabetes (Ozempic) in 2017 and for chronic weight management (Wegovy) in 2021. The STEP clinical trial program demonstrated average weight loss of 15-17% of body weight. The SELECT trial confirmed cardiovascular benefits.",
    relatedPeptideNames: ["Tirzepatide", "Liraglutide", "Exenatide", "Dulaglutide"],
  },
  "Tirzepatide": {
    primaryBenefit: "Dual-action blood sugar and weight management",
    shortSummary: "A first-in-class dual GIP/GLP-1 receptor agonist for diabetes and weight management.",
    benefits: "Tirzepatide activates both GIP and GLP-1 receptors, providing superior glycemic control and weight loss compared to single-agonist approaches. In clinical trials, it demonstrated up to 22.5% body weight reduction and significant HbA1c improvements.",
    administrationMethod: "Subcutaneous Injection",
    administrationDetails: "Administered as a once-weekly subcutaneous injection using a single-dose pen. Injected in the abdomen, thigh, or upper arm. Dose is gradually increased over weeks to minimize gastrointestinal side effects.",
    storage: "Store in a refrigerator at 2-8°C. May be kept at room temperature (up to 30°C) for up to 21 days. Do not freeze. Protect from light.",
    mechanism: "Tirzepatide is a synthetic peptide that simultaneously activates GIP and GLP-1 receptors. GIP receptor activation enhances insulin sensitivity and may improve fat metabolism, while GLP-1 receptor activation promotes insulin secretion and appetite suppression. The dual mechanism provides additive metabolic benefits.",
    useCases: ["Metabolic Health", "Fat Loss", "Cardiovascular"],
    stacks: [],
    safetyNotes: "Common side effects include nausea, diarrhea, and decreased appetite. Similar thyroid C-cell tumor warnings as other GLP-1 receptor agonists. Pancreatitis has been reported rarely.",
    researchBackground: "Developed by Eli Lilly. Approved as Mounjaro for T2D in 2022 and as Zepbound for weight management in 2023. The SURMOUNT trial program showed unprecedented weight loss results. The SURPASS trials demonstrated superior HbA1c reduction versus semaglutide.",
    relatedPeptideNames: ["Semaglutide", "Retatrutide", "Survodutide"],
  },
  "BPC-157": {
    primaryBenefit: "Tissue repair and gut healing",
    shortSummary: "A gastric pentadecapeptide researched for tissue-healing and anti-inflammatory properties.",
    benefits: "BPC-157 has been studied for its ability to accelerate healing of muscles, tendons, ligaments, and the gastrointestinal tract. Animal research suggests it may promote angiogenesis, reduce inflammation, and protect against NSAID-induced gut damage. It has shown potential for tendon-to-bone healing and nerve repair in preclinical models.",
    administrationMethod: "Subcutaneous Injection",
    administrationDetails: "Typically administered via subcutaneous injection near the site of injury in research settings. Oral administration has also been studied for gastrointestinal applications. Dosing protocols in research typically range from 200-800 mcg per day.",
    storage: "Store lyophilized powder at -20°C for long-term storage. Once reconstituted with bacteriostatic water, store at 2-8°C and use within 30 days. Protect from light and avoid repeated freeze-thaw cycles.",
    mechanism: "BPC-157 interacts with the nitric oxide system and upregulates growth hormone receptors. It promotes VEGF-mediated angiogenesis and has been shown to modulate serotonin, dopamine, and GABAergic systems. The peptide appears to enhance the FAK-paxillin pathway involved in cell migration and wound healing.",
    useCases: ["Recovery", "Gut Health", "Joint Support", "Anti-Inflammatory", "Wound Healing"],
    stacks: ["TB-500 (synergistic tissue repair)", "GHK-Cu (skin and tissue regeneration)"],
    safetyNotes: "Research is primarily from animal studies. Human clinical trial data is limited. No significant adverse effects have been reported in animal models, but the lack of large-scale human studies means the safety profile is not fully established.",
    researchBackground: "Originally isolated as a partial sequence from human gastric juice. Extensively studied by Dr. Predrag Sikiric and colleagues at the University of Zagreb since the 1990s. Over 100 published preclinical studies document its healing properties across various tissue types.",
    relatedPeptideNames: ["TB-500", "GHK-Cu", "Thymosin Beta-4"],
  },
  "TB-500": {
    primaryBenefit: "Tissue repair and inflammation reduction",
    shortSummary: "A synthetic fragment of Thymosin Beta-4 studied for tissue repair and anti-inflammatory effects.",
    benefits: "TB-500 promotes cell migration, blood vessel formation, and tissue repair. It has been studied for its ability to reduce inflammation, promote wound healing, and support recovery from muscle, tendon, and ligament injuries. Research suggests it may also have cardioprotective properties.",
    administrationMethod: "Subcutaneous Injection",
    administrationDetails: "Administered via subcutaneous injection. Research protocols typically use loading phases followed by maintenance dosing. Common research doses range from 2-5 mg administered twice weekly during loading.",
    storage: "Store lyophilized powder at -20°C. Once reconstituted with bacteriostatic water, store at 2-8°C and use within 14-21 days. Keep away from light.",
    mechanism: "TB-500 is a synthetic peptide representing the active region (amino acids 17-23) of Thymosin Beta-4. It binds to actin, promoting cell migration and proliferation. It upregulates actin expression, which is critical for cell movement to sites of injury. It also reduces inflammatory cytokine production.",
    useCases: ["Recovery", "Anti-Inflammatory", "Wound Healing", "Cardiovascular"],
    stacks: ["BPC-157 (synergistic tissue repair)", "GHK-Cu (collagen remodeling)"],
    safetyNotes: "Most research has been conducted in animal models. Human clinical data is limited. The peptide is related to Thymosin Beta-4 which has been studied in cardiac clinical trials with acceptable safety profiles.",
    researchBackground: "Derived from Thymosin Beta-4, first isolated from the thymus gland. Thymosin Beta-4 has been studied in clinical trials for wound healing and cardiac repair (RegeneRx Biopharmaceuticals). TB-500 represents the key active fragment responsible for tissue repair activity.",
    relatedPeptideNames: ["BPC-157", "Thymosin Beta-4", "Thymosin Alpha-1"],
  },
  "Thymosin Beta-4": {
    primaryBenefit: "Wound healing and tissue regeneration",
    shortSummary: "A naturally occurring 43-amino acid peptide involved in tissue repair and cell migration.",
    benefits: "Thymosin Beta-4 plays a key role in tissue repair, wound healing, and anti-inflammatory responses. It promotes keratinocyte migration, collagen deposition, and angiogenesis. It has been studied for corneal wound healing, cardiac tissue repair after myocardial infarction, and dermal wound closure.",
    administrationMethod: "Topical / Subcutaneous Injection",
    administrationDetails: "Available in research as injectable and topical formulations. For ophthalmic use, it has been studied as eye drops (RGN-259). Subcutaneous injection protocols vary based on the therapeutic target.",
    storage: "Store lyophilized form at -20°C. Reconstituted solutions should be refrigerated at 2-8°C. Topical formulations have specific stability profiles depending on the formulation base.",
    mechanism: "Thymosin Beta-4 sequesters G-actin monomers, regulating actin polymerization and thereby controlling cell migration. It promotes laminin-5 production for cell adhesion, stimulates hair follicle stem cells, and has anti-inflammatory effects through NF-kB pathway modulation.",
    useCases: ["Wound Healing", "Recovery", "Skin Health", "Anti-Inflammatory", "Hair Growth"],
    stacks: ["BPC-157 (complementary healing pathways)", "GHK-Cu (skin rejuvenation)"],
    safetyNotes: "Has been studied in clinical trials for ophthalmological indications with favorable safety data. As a naturally occurring peptide in human tissues, it has a well-understood physiological role.",
    researchBackground: "Discovered in the thymus gland. Thymosin Beta-4 is one of the most abundant intracellular peptides. RegeneRx Biopharmaceuticals developed it for clinical use. Phase 2 trials were conducted for corneal wound healing (RGN-259) and cardiac repair.",
    relatedPeptideNames: ["TB-500", "Thymosin Alpha-1", "BPC-157"],
  },
  "Thymosin Alpha-1": {
    primaryBenefit: "Immune system modulation and support",
    shortSummary: "An immunomodulatory peptide used to enhance immune function in chronic infections.",
    benefits: "Thymosin Alpha-1 enhances T-cell maturation and function, boosts natural killer cell activity, and improves dendritic cell function. It is approved in several countries for hepatitis B and C treatment and as an immune adjuvant. It has been studied for improving immune responses in immunocompromised patients.",
    administrationMethod: "Subcutaneous Injection",
    administrationDetails: "Administered as a subcutaneous injection, typically 1.6 mg twice weekly. Used clinically in over 35 countries under the brand name Zadaxin for hepatitis B and as an immune booster.",
    storage: "Store lyophilized vials at 2-25°C. Once reconstituted, use immediately or store at 2-8°C for up to 24 hours. Do not freeze the reconstituted solution.",
    mechanism: "Thymosin Alpha-1 acts on toll-like receptors (TLR2 and TLR9) in dendritic cells and macrophages, activating innate and adaptive immune pathways. It stimulates T-cell differentiation in the thymus, enhances cytokine production (IL-2, IFN-alpha), and promotes MHC class I antigen presentation.",
    useCases: ["Immune Support", "Anti-Inflammatory"],
    stacks: ["LL-37 (antimicrobial peptide for immune defense)"],
    safetyNotes: "Well-tolerated in clinical use with mild injection site reactions being the most common side effect. Has been used safely in thousands of patients across multiple countries. Approved as Zadaxin in over 35 countries.",
    researchBackground: "Originally isolated from thymic tissue by Dr. Allan Goldstein in the 1970s. Developed by SciClone Pharmaceuticals as Zadaxin. Approved in multiple countries for hepatitis B treatment. Has been investigated as an adjuvant therapy for various cancers and chronic infections.",
    relatedPeptideNames: ["Thymosin Beta-4", "TB-500", "LL-37"],
  },
  "CJC-1295": {
    primaryBenefit: "Growth hormone release stimulation",
    shortSummary: "A synthetic GHRH analog that stimulates sustained growth hormone release from the pituitary.",
    benefits: "CJC-1295 increases growth hormone and IGF-1 levels by mimicking growth hormone-releasing hormone. It promotes lean body mass, improved body composition, deeper sleep quality, and enhanced recovery. The DAC (Drug Affinity Complex) version provides extended duration of action.",
    administrationMethod: "Subcutaneous Injection",
    administrationDetails: "Administered via subcutaneous injection, typically before bedtime to align with natural GH secretion patterns. The DAC version is administered 1-2 times per week due to its extended half-life. The non-DAC version is often used daily.",
    storage: "Store lyophilized powder at -20°C. Reconstitute with bacteriostatic water and store at 2-8°C. Use reconstituted solution within 21 days. Avoid exposure to heat and light.",
    mechanism: "CJC-1295 is a synthetic analog of GHRH (growth hormone-releasing hormone) with amino acid substitutions that resist DPP-IV degradation. The DAC version covalently bonds to albumin in vivo, extending its half-life from minutes to approximately 8 days. It stimulates the GHRH receptor on pituitary somatotrophs.",
    useCases: ["Muscle Growth", "Recovery", "Anti-Aging", "Fat Loss", "Sleep"],
    stacks: ["Ipamorelin (synergistic GH release without cortisol/prolactin increase)", "Sermorelin (alternative GHRH analog)"],
    safetyNotes: "Research data suggests dose-dependent side effects including water retention, tingling in extremities, and increased hunger. The DAC version can cause sustained GH elevation that may not mimic natural pulsatile release patterns.",
    researchBackground: "Developed by ConjuChem Biotechnologies. A Phase 2 clinical trial evaluated CJC-1295 DAC for growth hormone deficiency. The tetrasubstituted GHRH(1-29) analog with DAC technology demonstrated significant and sustained GH/IGF-1 elevation in clinical studies.",
    relatedPeptideNames: ["Ipamorelin", "Sermorelin", "Tesamorelin"],
  },
  "Ipamorelin": {
    primaryBenefit: "Selective growth hormone secretion",
    shortSummary: "A selective growth hormone secretagogue that stimulates GH release without affecting cortisol or prolactin.",
    benefits: "Ipamorelin selectively stimulates growth hormone release with minimal impact on cortisol, prolactin, or appetite hormones. This selectivity makes it favorable for improving body composition, sleep quality, bone density, and recovery while minimizing unwanted hormonal side effects.",
    administrationMethod: "Subcutaneous Injection",
    administrationDetails: "Administered via subcutaneous injection, typically 2-3 times daily. Often taken before bedtime to enhance the natural nocturnal GH pulse. Dosing in research ranges from 100-300 mcg per injection.",
    storage: "Store lyophilized peptide at -20°C. After reconstitution with bacteriostatic water, store at 2-8°C and use within 21 days. Keep protected from light.",
    mechanism: "Ipamorelin is a pentapeptide that acts as a ghrelin/growth hormone secretagogue receptor (GHS-R) agonist. Unlike other GHS-R agonists, it does not stimulate ACTH or cortisol release, and has minimal effect on prolactin and appetite. It amplifies natural pulsatile GH release from the anterior pituitary.",
    useCases: ["Muscle Growth", "Anti-Aging", "Recovery", "Sleep", "Bone Health"],
    stacks: ["CJC-1295 (combined GHRH + GHSP synergy)", "Sermorelin (alternative GH-stimulating combination)"],
    safetyNotes: "Generally well-tolerated in research studies. Possible side effects include headache, lightheadedness, and injection site reactions. Its selectivity for GH release over cortisol is considered a favorable safety characteristic compared to other secretagogues.",
    researchBackground: "Developed by Novo Nordisk as NNC 26-0161. Studied in Phase 2 clinical trials for growth hormone deficiency and postoperative ileus. Published research demonstrates its high selectivity among growth hormone secretagogues.",
    relatedPeptideNames: ["CJC-1295", "Sermorelin", "GHRP-6"],
  },
  "AOD-9604": {
    primaryBenefit: "Fat metabolism support",
    shortSummary: "A modified fragment of human growth hormone studied for its fat-reducing properties.",
    benefits: "AOD-9604 is a peptide fragment corresponding to amino acids 177-191 of human growth hormone, modified with a tyrosine at the N-terminus. Research suggests it stimulates lipolysis (fat breakdown) and inhibits lipogenesis (fat formation) without affecting blood sugar or tissue growth, unlike full growth hormone.",
    administrationMethod: "Subcutaneous Injection",
    administrationDetails: "Administered via subcutaneous injection in research settings, typically in the abdominal area. Oral formulations have also been studied. Research dosing varies but commonly ranges from 250-500 mcg daily.",
    storage: "Store lyophilized form at -20°C. Reconstituted peptide should be refrigerated at 2-8°C and used within 21 days. Do not freeze reconstituted solution.",
    mechanism: "AOD-9604 mimics the lipolytic region of growth hormone without interacting with the growth hormone receptor in a way that promotes IGF-1 release or cellular growth. It activates beta-3 adrenergic receptors on adipocytes and enhances fat oxidation through a calcium-dependent pathway distinct from full-length GH signaling.",
    useCases: ["Fat Loss", "Metabolic Health"],
    stacks: ["CJC-1295/Ipamorelin (combined body composition approach)"],
    safetyNotes: "Clinical studies have not shown effects on blood glucose, IGF-1, or growth patterns. It has received GRAS (Generally Recognized as Safe) status from the FDA for use as a food substance. However, injectable use has not received regulatory approval.",
    researchBackground: "Developed by Metabolic Pharmaceuticals in Australia. Based on research by Professor Frank Ng at Monash University. Phase 2 clinical trials for obesity were conducted. Received FDA GRAS status in 2014 for oral use in food products.",
    relatedPeptideNames: ["CJC-1295", "Ipamorelin", "Semaglutide"],
  },
  "GHK-Cu": {
    primaryBenefit: "Skin rejuvenation and wound healing",
    shortSummary: "A copper-binding tripeptide naturally found in human plasma, studied for skin regeneration and anti-aging.",
    benefits: "GHK-Cu stimulates collagen and elastin production, promotes glycosaminoglycan synthesis, and supports skin remodeling. It has antioxidant and anti-inflammatory properties. Research shows it can improve skin firmness, reduce fine lines, accelerate wound healing, and promote hair follicle growth.",
    administrationMethod: "Topical / Subcutaneous Injection",
    administrationDetails: "Most commonly used topically in serums and creams at concentrations of 1-3%. Also available as a subcutaneous injectable for research. Topical application is typically twice daily to clean skin.",
    storage: "Store topical formulations per manufacturer instructions, typically at room temperature away from direct sunlight. Lyophilized injectable form should be stored at -20°C. Reconstituted solutions at 2-8°C.",
    mechanism: "GHK-Cu is a naturally occurring tripeptide (glycyl-L-histidyl-L-lysine) that chelates copper(II) ions. The copper complex activates wound healing genes, increases collagen I, III, and elastin synthesis, stimulates metalloproteinases for tissue remodeling, and recruits mast cells that release growth factors. It modulates over 4,000 human genes.",
    useCases: ["Skin Health", "Anti-Aging", "Wound Healing", "Hair Growth"],
    stacks: ["BPC-157 (tissue regeneration synergy)", "Thymosin Beta-4 (comprehensive wound healing)"],
    safetyNotes: "GHK-Cu has an excellent topical safety profile with decades of cosmetic use. It is a naturally occurring peptide in human plasma, with levels declining with age. Injectable use data is more limited.",
    researchBackground: "Discovered by Dr. Loren Pickart in the 1970s during studies of human albumin. Naturally found in human plasma, saliva, and urine. Over 60 years of research documents its wound healing and skin regeneration properties. Widely used in cosmeceutical products.",
    relatedPeptideNames: ["BPC-157", "Thymosin Beta-4", "Epitalon"],
  },
  "PT-141": {
    primaryBenefit: "Sexual function support",
    shortSummary: "A melanocortin receptor agonist approved for hypoactive sexual desire disorder in women.",
    benefits: "PT-141 (bremelanotide) activates melanocortin receptors in the central nervous system to enhance sexual desire. Unlike PDE5 inhibitors that act on blood flow, PT-141 works through the brain's arousal pathways. It is FDA-approved for premenopausal women with hypoactive sexual desire disorder (HSDD).",
    administrationMethod: "Subcutaneous Injection",
    administrationDetails: "Administered as a subcutaneous injection in the abdomen or thigh at least 45 minutes before anticipated sexual activity. The approved dose is 1.75 mg. Not to be used more than once within 24 hours or more than 8 times per month.",
    storage: "Store autoinjectors at room temperature 20-25°C. Protect from light. Do not freeze. Check expiration date on packaging.",
    mechanism: "PT-141 is a cyclic heptapeptide analog of alpha-MSH that activates melanocortin-4 receptors (MC4R) in the hypothalamus. MC4R activation in the medial preoptic area modulates sexual arousal pathways independent of vascular mechanisms. It also has minor activity at MC1R and MC3R.",
    useCases: ["Sexual Health"],
    stacks: [],
    safetyNotes: "FDA-approved as Vyleesi. Common side effects include nausea (40% of patients), flushing, headache, and injection site reactions. May cause transient increases in blood pressure. Contraindicated in patients with uncontrolled hypertension.",
    researchBackground: "Derived from Melanotan II during development by Palatin Technologies. Originally discovered as a byproduct of tanning peptide research. Approved by the FDA in 2019 as Vyleesi (bremelanotide) for HSDD in premenopausal women.",
    relatedPeptideNames: ["Melanotan II", "Setmelanotide", "Afamelanotide"],
  },
  "DSIP": {
    primaryBenefit: "Sleep regulation and stress reduction",
    shortSummary: "Delta Sleep-Inducing Peptide, a neuromodulator studied for sleep promotion and stress adaptation.",
    benefits: "DSIP has been studied for its ability to promote delta wave (deep) sleep, normalize circadian rhythms, and modulate stress responses. Research suggests it may help regulate cortisol levels, improve sleep architecture, and have analgesic properties. It has also been investigated for its effects on opiate withdrawal.",
    administrationMethod: "Subcutaneous Injection / Intranasal",
    administrationDetails: "Administered via subcutaneous injection or intranasal spray in research protocols. Typically dosed in the evening 1-2 hours before sleep. Research doses range from 100-300 mcg.",
    storage: "Store lyophilized powder at -20°C. Reconstituted solution should be refrigerated at 2-8°C and used within 14 days. DSIP is relatively fragile and degrades quickly in solution.",
    mechanism: "DSIP modulates central neurotransmitter systems, including serotonergic and glutamatergic pathways. It appears to act on the hypothalamus and limbic system to promote slow-wave sleep. It may also modulate ACTH and cortisol release, contributing to stress adaptation. The exact receptor target remains under investigation.",
    useCases: ["Sleep", "Cognitive Support", "Neuroprotection"],
    stacks: ["Epitalon (anti-aging sleep support)"],
    safetyNotes: "Research data is primarily from animal studies and small human trials conducted in the 1980s-90s. Long-term safety data is limited. No major adverse effects were reported in early clinical studies.",
    researchBackground: "Discovered in 1977 by Schoenenberger and Monnier from cerebral venous blood of rabbits during induced sleep. Several clinical studies were conducted in Europe in the 1980s and 1990s for insomnia and chronic pain. Interest has renewed with modern sleep research.",
    relatedPeptideNames: ["Epitalon", "Selank", "Semax"],
  },
  "Melanotan II": {
    primaryBenefit: "Melanogenesis stimulation (skin tanning)",
    shortSummary: "A synthetic melanocortin peptide that stimulates melanin production and has been studied for tanning effects.",
    benefits: "Melanotan II stimulates melanocyte receptors to increase melanin production, resulting in skin darkening without UV exposure. It has also been researched for its effects on sexual arousal and appetite suppression through melanocortin receptor activation.",
    administrationMethod: "Subcutaneous Injection",
    administrationDetails: "Administered via subcutaneous injection in research contexts. Typical research protocols involve an initial loading phase of low doses followed by maintenance dosing. Often administered before UV exposure in research settings.",
    storage: "Store lyophilized powder at -20°C protected from light. Reconstitute with bacteriostatic water and store at 2-8°C. Use within 30 days of reconstitution.",
    mechanism: "Melanotan II is a non-selective melanocortin receptor agonist, activating MC1R (melanogenesis), MC3R (energy homeostasis), MC4R (sexual arousal, appetite), and MC5R. Its primary tanning effect comes from MC1R activation on melanocytes, stimulating eumelanin synthesis. MC4R activation accounts for its sexual function and appetite effects.",
    useCases: ["Skin Health"],
    stacks: [],
    safetyNotes: "Not approved by any regulatory authority. Reported side effects include nausea, facial flushing, fatigue, and changes in existing moles. There are concerns about potential effects on melanocytic nevi. Not recommended due to lack of regulatory approval and safety monitoring.",
    researchBackground: "Developed at the University of Arizona by Dr. Victor Hruby and colleagues in the 1990s as a potential sunless tanning agent. Led to the development of PT-141 (bremelanotide) and afamelanotide (Scenesse), which both received regulatory approval for specific indications.",
    relatedPeptideNames: ["PT-141", "Afamelanotide", "Setmelanotide"],
  },
  "MOTS-c": {
    primaryBenefit: "Metabolic regulation and exercise mimetic",
    shortSummary: "A mitochondria-derived peptide that regulates metabolic homeostasis and has exercise-mimetic properties.",
    benefits: "MOTS-c improves insulin sensitivity, enhances glucose uptake in skeletal muscle, and activates AMPK — a key metabolic energy sensor. It has been described as an exercise mimetic because it activates similar metabolic pathways to physical exercise. Research suggests it may protect against age-related metabolic decline.",
    administrationMethod: "Subcutaneous Injection",
    administrationDetails: "Administered via subcutaneous injection in research settings. Dosing protocols vary in published research. It is encoded in the mitochondrial genome and naturally circulates in the bloodstream.",
    storage: "Store lyophilized form at -20°C. Reconstituted solution should be stored at 2-8°C and used within 14 days. Handle with care as it is sensitive to degradation.",
    mechanism: "MOTS-c is a 16-amino acid peptide encoded by the mitochondrial 12S rRNA gene. It activates the AMPK pathway, increasing glucose uptake and fatty acid oxidation in skeletal muscle. It translocates to the nucleus under metabolic stress, regulating nuclear gene expression related to antioxidant defense and metabolic adaptation.",
    useCases: ["Metabolic Health", "Anti-Aging", "Fat Loss", "Muscle Growth"],
    stacks: [],
    safetyNotes: "As a naturally occurring mitochondria-derived peptide, MOTS-c is part of normal human physiology. Research is still in early stages and human clinical data is limited. Levels naturally decline with age.",
    researchBackground: "Discovered in 2015 by Dr. Changhan David Lee at the University of Southern California. Published in Cell Metabolism, it was the first mitochondria-derived peptide shown to regulate nuclear gene expression. Ongoing research explores its therapeutic potential in metabolic disease and aging.",
    relatedPeptideNames: ["AOD-9604", "Epitalon"],
  },
  "Kisspeptin": {
    primaryBenefit: "Reproductive hormone regulation",
    shortSummary: "A neuropeptide that plays a central role in regulating reproductive hormone release and puberty onset.",
    benefits: "Kisspeptin is a key regulator of the hypothalamic-pituitary-gonadal axis. It stimulates GnRH release, which in turn triggers LH and FSH secretion. Research has explored its use in fertility treatment, particularly for triggering oocyte maturation in IVF, and in diagnosing reproductive disorders.",
    administrationMethod: "Subcutaneous Injection / IV Infusion",
    administrationDetails: "Administered as a single subcutaneous injection or intravenous infusion in clinical research settings. In IVF protocols, a single bolus injection has been studied as a trigger for oocyte maturation.",
    storage: "Store lyophilized form at -20°C. Reconstitute per research protocol. Reconstituted solutions should be used within hours due to peptide instability.",
    mechanism: "Kisspeptin binds to the GPR54 (KISS1R) receptor on GnRH neurons in the hypothalamus, stimulating GnRH pulsatile release. This cascade activates pituitary gonadotroph cells to release LH and FSH. Kisspeptin neurons integrate metabolic, photoperiodic, and stress signals to regulate reproductive function.",
    useCases: ["Sexual Health", "Metabolic Health"],
    stacks: [],
    safetyNotes: "Generally well-tolerated in clinical studies. May cause transient headache and abdominal discomfort. Its physiological action on the reproductive axis means it should be used with appropriate medical oversight.",
    researchBackground: "The kisspeptin gene (KISS1) was identified as a metastasis suppressor in melanoma in 1996. Its role in reproductive physiology was discovered in 2003 when loss-of-function mutations in GPR54 were found to cause hypogonadotropic hypogonadism. Clinical trials at Imperial College London have studied it for IVF triggering.",
    relatedPeptideNames: ["Gonadorelin", "Leuprolide", "Goserelin"],
  },
  "Sermorelin": {
    primaryBenefit: "Natural growth hormone stimulation",
    shortSummary: "A GHRH analog that stimulates the pituitary to release growth hormone naturally.",
    benefits: "Sermorelin stimulates the pituitary gland to produce and secrete growth hormone in a pulsatile, physiological manner. It supports lean body mass, improved sleep quality, enhanced recovery, and favorable body composition changes while maintaining the body's natural feedback mechanisms for GH regulation.",
    administrationMethod: "Subcutaneous Injection",
    administrationDetails: "Administered via subcutaneous injection, typically before bedtime to align with natural GH secretion. Previously available as Geref for GH deficiency testing. Dosing in clinical settings typically ranges from 100-300 mcg.",
    storage: "Store lyophilized powder at 2-8°C. After reconstitution with bacteriostatic water, refrigerate and use within 14 days. Do not freeze.",
    mechanism: "Sermorelin is a synthetic peptide consisting of the first 29 amino acids of human GHRH (the biologically active fragment). It binds to GHRH receptors on pituitary somatotrophs, stimulating GH synthesis and secretion. Unlike exogenous GH, it preserves the negative feedback loop via IGF-1 and somatostatin.",
    useCases: ["Anti-Aging", "Muscle Growth", "Recovery", "Sleep"],
    stacks: ["Ipamorelin (GHRH + GHSP synergy)", "CJC-1295 (extended-duration GHRH stimulation)"],
    safetyNotes: "Previously FDA-approved as Geref Diagnostic for GH deficiency testing. Common side effects include injection site reactions, flushing, and headache. Generally well-tolerated due to its preservation of natural GH feedback mechanisms.",
    researchBackground: "Developed by Serono Laboratories. Approved by the FDA in 1997 as Geref for diagnostic use. Has been used clinically for growth hormone deficiency assessment. Multiple studies have demonstrated its ability to restore GH secretion in aging adults.",
    relatedPeptideNames: ["CJC-1295", "Ipamorelin", "Tesamorelin", "GHRP-6"],
  },
  "Tesamorelin": {
    primaryBenefit: "Visceral fat reduction",
    shortSummary: "An FDA-approved GHRH analog used to reduce excess abdominal fat in HIV-associated lipodystrophy.",
    benefits: "Tesamorelin effectively reduces visceral adipose tissue (VAT), improves lipid profiles, and lowers triglycerides. It stimulates growth hormone release to target visceral fat without significantly affecting subcutaneous fat or lean mass. It has also been studied for cognitive benefits through IGF-1 elevation.",
    administrationMethod: "Subcutaneous Injection",
    administrationDetails: "Administered as a once-daily subcutaneous injection of 2 mg in the abdomen. The area of injection should be rotated to avoid lipodystrophy. FDA-approved as Egrifta for HIV-associated lipodystrophy.",
    storage: "Store vials at room temperature 20-25°C. Reconstitute with provided sterile water diluent. Use reconstituted solution immediately. Do not freeze.",
    mechanism: "Tesamorelin is a synthetic GHRH analog with a trans-3-hexenoic acid modification that improves stability. It binds to pituitary GHRH receptors, stimulating GH release that preferentially mobilizes visceral adipose tissue through enhanced lipolysis. The mechanism preserves physiological GH feedback.",
    useCases: ["Fat Loss", "Metabolic Health", "Cognitive Support"],
    stacks: ["Ipamorelin (enhanced GH secretion)"],
    safetyNotes: "FDA-approved with well-characterized safety profile. Common side effects include injection site reactions, joint pain, and peripheral edema. May cause fluid retention and carpal tunnel-like symptoms. Contraindicated in active malignancy.",
    researchBackground: "Developed by Theratechnologies. Approved by the FDA in 2010 as Egrifta for HIV-associated lipodystrophy. Phase 3 trials demonstrated significant VAT reduction. Ongoing research examines cognitive benefits and potential NASH applications.",
    relatedPeptideNames: ["Sermorelin", "CJC-1295", "Ipamorelin"],
  },
  "Epitalon": {
    primaryBenefit: "Telomerase activation and anti-aging",
    shortSummary: "A synthetic tetrapeptide studied for its ability to activate telomerase and regulate cellular aging.",
    benefits: "Epitalon (also known as Epithalon) has been studied for its ability to activate telomerase, the enzyme that lengthens telomeres — the protective caps on chromosomes that shorten with aging. Research suggests it may support melatonin production, regulate neuroendocrine function, and have antioxidant properties.",
    administrationMethod: "Subcutaneous Injection",
    administrationDetails: "Administered via subcutaneous injection in research settings. Typical research protocols use 5-10 mg daily for 10-20 day cycles with periodic breaks. Intranasal and transdermal formulations have also been explored.",
    storage: "Store lyophilized powder at -20°C. Reconstituted solution should be stored at 2-8°C and used within 14 days. Protect from light.",
    mechanism: "Epitalon (Ala-Glu-Asp-Gly) activates telomerase by inducing expression of the hTERT (human telomerase reverse transcriptase) gene. It also stimulates pineal gland function, increasing melatonin production. The peptide may regulate gene expression patterns associated with aging and circadian rhythm maintenance.",
    useCases: ["Anti-Aging", "Sleep", "Immune Support"],
    stacks: ["GHK-Cu (comprehensive anti-aging)", "DSIP (sleep and circadian support)"],
    safetyNotes: "Research is primarily from Russian studies led by Dr. Vladimir Khavinson. Human studies have been small in scale. As a short tetrapeptide, it has shown good tolerability in published research. Large-scale clinical trials have not been conducted.",
    researchBackground: "Developed by Dr. Vladimir Khavinson at the St. Petersburg Institute of Bioregulation and Gerontology. Based on research into epithalamin (a pineal gland extract). Published studies in animals demonstrated lifespan extension and telomerase activation. Human studies showed melatonin normalization in elderly subjects.",
    relatedPeptideNames: ["GHK-Cu", "DSIP", "MOTS-c"],
  },
  "LL-37": {
    primaryBenefit: "Antimicrobial defense and immune modulation",
    shortSummary: "The only human cathelicidin antimicrobial peptide, involved in innate immune defense and wound healing.",
    benefits: "LL-37 has broad-spectrum antimicrobial activity against bacteria, viruses, and fungi. Beyond direct antimicrobial action, it modulates immune responses by recruiting immune cells, promoting wound healing, stimulating angiogenesis, and regulating inflammatory responses. It has been studied for potential applications in chronic wound treatment.",
    administrationMethod: "Topical / IV Infusion",
    administrationDetails: "Primarily studied as topical application for wound healing and infection control. Intravenous and intratumoral administration have been explored in cancer research. Topical formulations vary by research application.",
    storage: "Store lyophilized form at -20°C. Reconstituted solutions should be stored at 2-8°C. Use within 7 days of reconstitution. LL-37 can adsorb to plastic surfaces, so use low-binding containers.",
    mechanism: "LL-37 disrupts bacterial membranes through electrostatic interactions with negatively charged phospholipids. It also acts as a signaling molecule, binding to formyl peptide receptor-like 1 (FPRL1) and P2X7 receptor to modulate immune cell chemotaxis and cytokine production. It promotes keratinocyte migration for wound closure.",
    useCases: ["Immune Support", "Anti-Inflammatory", "Wound Healing"],
    stacks: ["Thymosin Alpha-1 (immune system support)"],
    safetyNotes: "As a naturally occurring human peptide, its physiological role is well understood. At high concentrations, it can be cytotoxic to host cells. Clinical application requires careful dosing. Research is actively exploring modified versions with improved therapeutic windows.",
    researchBackground: "LL-37 is the only human cathelicidin, processed from the precursor protein hCAP-18. Discovered in the 1990s, it is expressed in neutrophils, epithelial cells, and macrophages. Extensive research documents its role in innate immunity. Clinical trials have explored its use in wound healing and cancer immunotherapy.",
    relatedPeptideNames: ["Thymosin Alpha-1", "BPC-157"],
  },
  "Selank": {
    primaryBenefit: "Anxiety reduction and cognitive enhancement",
    shortSummary: "A synthetic peptide derived from tuftsin, developed as an anxiolytic and nootropic agent.",
    benefits: "Selank has been studied for its anxiolytic (anti-anxiety) effects without sedation or cognitive impairment. It enhances memory, attention, and learning while reducing anxiety. It also has immunomodulatory properties and may support stable mood and stress resilience.",
    administrationMethod: "Intranasal",
    administrationDetails: "Primarily administered as an intranasal spray. The approved formulation in Russia is a 0.15% nasal spray. Typical dosing is 2-3 drops in each nostril, 2-3 times daily. The intranasal route provides rapid access to the CNS.",
    storage: "Store nasal spray formulation at 2-8°C. Protect from light. Use within the recommended timeframe after opening per manufacturer guidelines.",
    mechanism: "Selank is a synthetic heptapeptide analog of the immunomodulatory peptide tuftsin with an added Pro-Gly-Pro sequence for metabolic stability. It modulates GABA-A receptor expression, influences the balance of Th1/Th2 cytokines, and affects enkephalin and serotonin metabolism. It also inhibits enzymes that degrade enkephalins.",
    useCases: ["Cognitive Support", "Neuroprotection", "Immune Support"],
    stacks: ["Semax (complementary nootropic)", "DSIP (stress management and sleep)"],
    safetyNotes: "Approved in Russia as a nasal spray for anxiety and neurasthenia. Reported to have a favorable safety profile with no addictive potential or withdrawal effects. Does not cause sedation or impair motor function.",
    researchBackground: "Developed at the Institute of Molecular Genetics of the Russian Academy of Sciences. Based on the naturally occurring immunopeptide tuftsin. Approved in Russia for clinical use. Published studies demonstrate anxiolytic effects comparable to benzodiazepines but without sedation or dependence.",
    relatedPeptideNames: ["Semax", "DSIP", "Epitalon"],
  },
  "Semax": {
    primaryBenefit: "Neuroprotection and cognitive enhancement",
    shortSummary: "A synthetic analog of ACTH(4-10) developed as a nootropic and neuroprotective agent.",
    benefits: "Semax enhances memory, attention, and learning capacity. It has neuroprotective effects against oxidative stress and ischemic damage. Research shows it promotes brain-derived neurotrophic factor (BDNF) expression, supports neuronal survival, and may accelerate recovery from brain injuries.",
    administrationMethod: "Intranasal",
    administrationDetails: "Administered as intranasal drops. The approved formulation in Russia is a 0.1% or 1% nasal solution. Typical dosing is 2-3 drops in each nostril, 2-3 times daily. Higher concentration (1%) is used for acute neurological conditions.",
    storage: "Store at 2-8°C. Protect from light. Nasal solution should be used within the recommended period after opening. Do not freeze.",
    mechanism: "Semax is a synthetic heptapeptide analog of the ACTH fragment (amino acids 4-10) with a Pro-Gly-Pro C-terminal extension for stability. It does not affect adrenal cortisol production. Instead, it activates melanocortin receptors (MC3R/MC4R) in the brain, stimulates BDNF and NGF expression, and modulates serotonergic and dopaminergic neurotransmission.",
    useCases: ["Cognitive Support", "Neuroprotection", "Recovery"],
    stacks: ["Selank (combined anxiolytic-nootropic)", "Epitalon (anti-aging neuroprotection)"],
    safetyNotes: "Approved in Russia and Ukraine for clinical use in stroke recovery and cognitive disorders. Has a favorable safety profile with minimal reported side effects. No evidence of tolerance or dependence. Not a stimulant.",
    researchBackground: "Developed at the Institute of Molecular Genetics, Russian Academy of Sciences, in the 1980s. Approved in Russia for treatment of stroke, cognitive disorders, and peptic ulcers. Extensive Russian-language literature supports its neuroprotective and nootropic effects.",
    relatedPeptideNames: ["Selank", "DSIP", "Epitalon"],
  },
  "Gonadorelin": {
    primaryBenefit: "Luteinizing hormone stimulation",
    shortSummary: "A synthetic GnRH (gonadotropin-releasing hormone) used to stimulate or test pituitary LH/FSH release.",
    benefits: "Gonadorelin stimulates the pituitary gland to release luteinizing hormone (LH) and follicle-stimulating hormone (FSH). It is used clinically to diagnose hypogonadism, treat delayed puberty, and support fertility. In research, it is studied for maintaining testicular function during hormone therapies.",
    administrationMethod: "Subcutaneous Injection / IV Infusion",
    administrationDetails: "Administered via subcutaneous or intravenous injection. For diagnostic use, a single injection is given and LH response is measured. For therapeutic use, pulsatile administration via a pump may be used to mimic natural GnRH release.",
    storage: "Store lyophilized powder at room temperature 15-25°C. Reconstitute with provided diluent. Use reconstituted solution within the timeframe specified by the manufacturer.",
    mechanism: "Gonadorelin is identical to endogenous GnRH (a decapeptide). It binds to GnRH receptors on anterior pituitary gonadotroph cells, triggering LH and FSH release. Pulsatile administration maintains receptor sensitivity, while continuous administration causes receptor downregulation and paradoxical suppression of gonadotropins.",
    useCases: ["Sexual Health", "Metabolic Health"],
    stacks: [],
    safetyNotes: "FDA-approved for diagnostic use (Factrel). Side effects are generally mild and include headache, nausea, and flushing. Continuous (non-pulsatile) administration can paradoxically suppress reproductive hormones.",
    researchBackground: "GnRH was characterized by Andrew Schally (Nobel Prize, 1977) and Roger Guillemin. Synthetic gonadorelin has been used clinically for decades. It forms the basis for both GnRH agonist and antagonist drug classes used in oncology and reproductive medicine.",
    relatedPeptideNames: ["Kisspeptin", "Leuprolide", "Goserelin", "Degarelix"],
  },
  "Liraglutide": {
    primaryBenefit: "Blood sugar control and weight loss",
    shortSummary: "A once-daily GLP-1 receptor agonist for type 2 diabetes and chronic weight management.",
    benefits: "Liraglutide improves glycemic control, promotes significant weight loss, and has demonstrated cardiovascular benefits. As a GLP-1 analog, it stimulates insulin secretion, suppresses glucagon, slows gastric emptying, and reduces appetite through central nervous system mechanisms.",
    administrationMethod: "Subcutaneous Injection",
    administrationDetails: "Administered as a once-daily subcutaneous injection at any time of day, independent of meals. Available as Victoza (for T2D, up to 1.8 mg) and Saxenda (for weight management, 3.0 mg). Dose is gradually titrated over weeks.",
    storage: "Store unused pens in refrigerator at 2-8°C. After first use, store at room temperature (up to 30°C) or refrigerated for 30 days. Do not freeze. Keep pen cap on when not in use.",
    mechanism: "Liraglutide is a GLP-1 analog with 97% homology to native GLP-1 and a C-16 palmitoyl fatty acid attached via a glutamic acid spacer. This modification enables albumin binding, extending half-life to ~13 hours. It activates the GLP-1 receptor on pancreatic beta cells, hypothalamic neurons, and cardiac tissue.",
    useCases: ["Metabolic Health", "Fat Loss", "Cardiovascular"],
    stacks: [],
    safetyNotes: "FDA-approved with extensive safety data. Common side effects include nausea, vomiting, and diarrhea. Thyroid C-cell tumor boxed warning based on rodent studies. The LEADER trial demonstrated cardiovascular safety and benefit.",
    researchBackground: "Developed by Novo Nordisk. Approved as Victoza in 2010 and Saxenda in 2014. The LEADER cardiovascular outcomes trial (9,340 patients) demonstrated significant reduction in major cardiovascular events. One of the most extensively studied GLP-1 agonists.",
    relatedPeptideNames: ["Semaglutide", "Exenatide", "Dulaglutide"],
  },
  "Octreotide": {
    primaryBenefit: "Growth hormone and gastrointestinal hormone suppression",
    shortSummary: "A synthetic somatostatin analog used to treat acromegaly, carcinoid syndrome, and neuroendocrine tumors.",
    benefits: "Octreotide suppresses growth hormone, glucagon, and insulin secretion. It reduces symptoms of carcinoid syndrome (flushing, diarrhea) and controls tumor growth in neuroendocrine tumors. It has antiproliferative effects and reduces splanchnic blood flow.",
    administrationMethod: "Subcutaneous Injection / Intramuscular",
    administrationDetails: "Available as immediate-release subcutaneous injection (Sandostatin, 2-3 times daily) or long-acting depot injection (Sandostatin LAR, once monthly intramuscularly). LAR formulation provides sustained release over 4 weeks.",
    storage: "Store at 2-8°C. Sandostatin LAR kits should be stored refrigerated. Immediate-release vials can be stored at room temperature for up to 14 days. Protect from light.",
    mechanism: "Octreotide is a cyclic octapeptide that selectively binds somatostatin receptors SSTR2 and SSTR5. By activating these receptors, it inhibits GH, TSH, and GI hormone secretion. It reduces portal blood flow and inhibits gallbladder contractility. Antiproliferative effects are mediated through cell cycle arrest and apoptosis induction.",
    useCases: ["Metabolic Health"],
    stacks: [],
    safetyNotes: "Well-characterized safety profile with decades of clinical use. Common side effects include gallstone formation (due to gallbladder stasis), GI disturbances, and injection site pain. Blood glucose monitoring is recommended due to effects on insulin and glucagon.",
    researchBackground: "Developed by Sandoz (now Novartis). Approved by the FDA in 1988. One of the first synthetic somatostatin analogs. Has been used for over 35 years in clinical practice. The CLARINET and PROMID trials demonstrated antitumor effects in neuroendocrine tumors.",
    relatedPeptideNames: ["Pasireotide", "Lanreotide"],
  },
  "Exenatide": {
    primaryBenefit: "Blood sugar regulation from natural peptide source",
    shortSummary: "A GLP-1 receptor agonist derived from Gila monster venom for type 2 diabetes treatment.",
    benefits: "Exenatide improves glycemic control by enhancing glucose-dependent insulin secretion, suppressing glucagon, and slowing gastric emptying. It promotes modest weight loss and has a unique origin as a synthetic version of exendin-4 from Gila monster saliva.",
    administrationMethod: "Subcutaneous Injection",
    administrationDetails: "Available as twice-daily injection (Byetta, 5-10 mcg) or once-weekly extended-release microsphere injection (Bydureon, 2 mg). Byetta is administered within 60 minutes before morning and evening meals.",
    storage: "Byetta pens: refrigerate at 2-8°C before first use. After first use, keep at room temperature up to 25°C for 30 days. Bydureon: refrigerate until use. Can be kept at room temperature for up to 4 weeks.",
    mechanism: "Exenatide is a 39-amino acid peptide with 53% homology to human GLP-1. Derived from exendin-4, it resists DPP-IV degradation more effectively than native GLP-1. It activates GLP-1 receptors on beta cells, suppresses glucagon from alpha cells, and acts on brainstem/hypothalamic circuits to reduce food intake.",
    useCases: ["Metabolic Health", "Fat Loss"],
    stacks: [],
    safetyNotes: "FDA-approved since 2005 with extensive safety data. Common side effects are gastrointestinal (nausea, vomiting). Reports of acute pancreatitis led to post-marketing surveillance. Anti-exenatide antibodies may develop but rarely affect efficacy.",
    researchBackground: "Originally isolated from Gila monster (Heloderma suspectum) saliva by Dr. John Eng in 1992. Developed by Amylin Pharmaceuticals. The first GLP-1 receptor agonist approved for T2D. Demonstrated the therapeutic potential of the GLP-1 pathway and paved the way for the entire incretin drug class.",
    relatedPeptideNames: ["Semaglutide", "Liraglutide", "Dulaglutide"],
  },
  "Leuprolide": {
    primaryBenefit: "Reproductive hormone suppression",
    shortSummary: "A GnRH superagonist that suppresses sex hormone production for cancer and reproductive conditions.",
    benefits: "Leuprolide suppresses testosterone and estrogen production by desensitizing pituitary GnRH receptors. It is widely used in prostate cancer treatment, endometriosis, uterine fibroids, precocious puberty, and as part of IVF protocols. Depot formulations provide sustained suppression for 1-6 months.",
    administrationMethod: "Subcutaneous Injection / Intramuscular",
    administrationDetails: "Available in multiple depot formulations: monthly, 3-month, 4-month, and 6-month injections. Also available as daily subcutaneous injections. Lupron Depot is administered intramuscularly, while Eligard is subcutaneous.",
    storage: "Store at room temperature 25°C (Eligard) or refrigerated at 2-8°C (Lupron Depot). Reconstitute immediately before injection. Do not freeze.",
    mechanism: "Leuprolide is a nonapeptide GnRH superagonist. Initial administration causes a transient surge in LH/FSH and sex hormones (flare effect). Continuous exposure downregulates GnRH receptors through receptor internalization and desensitization, ultimately suppressing gonadotropin and sex hormone production to castrate/menopausal levels.",
    useCases: ["Metabolic Health"],
    stacks: [],
    safetyNotes: "FDA-approved with well-established safety profile. Side effects relate to hormone suppression: hot flashes, bone density loss, mood changes, and sexual dysfunction. Initial flare effect in prostate cancer may require anti-androgen cover. Long-term use requires bone density monitoring.",
    researchBackground: "One of the first GnRH agonists developed, approved by the FDA in 1985 (Lupron). Developed by TAP Pharmaceuticals (now AbbVie). Has been a cornerstone of prostate cancer treatment for nearly 40 years. Multiple depot formulations have extended its clinical utility.",
    relatedPeptideNames: ["Goserelin", "Degarelix", "Gonadorelin"],
  },
  "Dulaglutide": {
    primaryBenefit: "Weekly blood sugar control",
    shortSummary: "A once-weekly GLP-1 receptor agonist with Fc fusion for sustained diabetes management.",
    benefits: "Dulaglutide provides sustained glycemic control with once-weekly dosing convenience. It reduces HbA1c, promotes weight loss, and has demonstrated cardiovascular benefits. The Fc fusion design provides a long half-life without the need for fatty acid or PEG modifications.",
    administrationMethod: "Subcutaneous Injection",
    administrationDetails: "Administered as a once-weekly subcutaneous injection using a single-use pen. Available in 0.75 mg and 1.5 mg doses. Can be injected in the abdomen, thigh, or upper arm. No dose titration required for the starting dose.",
    storage: "Store in refrigerator at 2-8°C. May be kept at room temperature up to 30°C for up to 14 days. Do not freeze. Keep in original carton to protect from light.",
    mechanism: "Dulaglutide consists of a GLP-1 analog covalently linked to a modified human IgG4 Fc fragment via a small peptide linker. The Fc fusion provides extended half-life (~5 days) through reduced renal clearance and FcRn-mediated recycling. It activates GLP-1 receptors for glucose-dependent insulin secretion.",
    useCases: ["Metabolic Health", "Cardiovascular"],
    stacks: [],
    safetyNotes: "FDA-approved as Trulicity. Common side effects include GI symptoms. The REWIND trial demonstrated cardiovascular benefit even in a broad diabetic population. Same thyroid C-cell tumor class warning as other GLP-1 agonists.",
    researchBackground: "Developed by Eli Lilly. Approved in 2014. The REWIND cardiovascular outcomes trial demonstrated significant reduction in major cardiovascular events in a diverse T2D population, including patients without established cardiovascular disease.",
    relatedPeptideNames: ["Semaglutide", "Liraglutide", "Exenatide"],
  },
  "Desmopressin": {
    primaryBenefit: "Water balance regulation and bleeding control",
    shortSummary: "A synthetic vasopressin analog for diabetes insipidus, bedwetting, and bleeding disorders.",
    benefits: "Desmopressin concentrates urine and reduces urine output by acting on kidney V2 receptors. It is used to treat central diabetes insipidus, primary nocturnal enuresis (bedwetting), and nocturia. It also increases clotting factor VIII and von Willebrand factor levels for bleeding control.",
    administrationMethod: "Intranasal / Oral / Subcutaneous Injection",
    administrationDetails: "Available as nasal spray (DDAVP, Stimate), oral tablets (DDAVP, Nocdurna), sublingual tablets, and injectable. Dosing varies by indication. For nocturia, sublingual Nocdurna is taken 30-60 minutes before bedtime.",
    storage: "Store nasal sprays and tablets at room temperature 20-25°C. Injectable formulation should be refrigerated at 2-8°C. Keep nasal spray upright.",
    mechanism: "Desmopressin is a modified vasopressin with deamination of position 1 cysteine and D-arginine at position 8. These changes eliminate vasopressor activity (V1R) while enhancing antidiuretic potency (V2R) and extending half-life. V2R activation in renal collecting ducts inserts aquaporin-2 channels, increasing water reabsorption.",
    useCases: ["Metabolic Health"],
    stacks: [],
    safetyNotes: "FDA-approved with decades of clinical use. Main risk is hyponatremia (low sodium) from water retention. Fluid intake should be restricted. Serum sodium monitoring is recommended. Contraindicated in habitual polydipsia.",
    researchBackground: "Developed in the 1960s by modifying vasopressin. One of the earliest successful peptide drug designs. Approved for diabetes insipidus, hemophilia A, and von Willebrand disease. The sublingual Nocdurna formulation was approved in 2018 for nocturia.",
    relatedPeptideNames: [],
  },
  "Ziconotide": {
    primaryBenefit: "Severe chronic pain management",
    shortSummary: "A synthetic cone snail venom peptide for severe chronic pain refractory to other treatments.",
    benefits: "Ziconotide provides potent analgesia for severe chronic pain that has not responded to other treatments. It acts through a completely different mechanism than opioids, offering pain relief without the risks of tolerance, physical dependence, or respiratory depression associated with opioid therapy.",
    administrationMethod: "Intrathecal",
    administrationDetails: "Administered exclusively via intrathecal infusion using an implanted programmable pump (e.g., Medtronic SynchroMed). Requires surgical pump implantation. Dosing starts very low and is slowly titrated over weeks. Not suitable for oral, IV, or epidural administration.",
    storage: "Store vials at 2-8°C. Do not freeze. Protect from light. Once transferred to pump, stable in the pump reservoir for up to 84 days at 37°C.",
    mechanism: "Ziconotide is a synthetic version of ω-conotoxin MVIIA from the marine cone snail Conus magus. It selectively blocks N-type voltage-gated calcium channels (Cav2.2) in the dorsal horn of the spinal cord. This prevents neurotransmitter release from primary afferent nociceptive neurons, interrupting pain signal transmission.",
    useCases: ["Neuroprotection"],
    stacks: [],
    safetyNotes: "FDA-approved as Prialt. Has significant neuropsychiatric side effects including hallucinations, confusion, mood changes, and cognitive impairment. Requires careful dose titration. CK (creatine kinase) elevation occurs frequently. Not for IV use — can cause severe adverse effects if administered systemically.",
    researchBackground: "Derived from the venom of Conus magus cone snail. Developed by Elan Pharmaceuticals (now Azur Pharma/Jazz). Approved by the FDA in 2004. Represents one of the most successful examples of marine-derived drug development. Over 200 publications document its analgesic properties.",
    relatedPeptideNames: ["Difelikefalin"],
  },
  "Carfilzomib": {
    primaryBenefit: "Multiple myeloma treatment",
    shortSummary: "An irreversible proteasome inhibitor for relapsed or refractory multiple myeloma.",
    benefits: "Carfilzomib provides potent and selective proteasome inhibition for cancer treatment. It demonstrates improved selectivity over first-generation proteasome inhibitors, with less peripheral neuropathy. It is effective in bortezomib-resistant myeloma due to its irreversible binding mechanism.",
    administrationMethod: "IV Infusion",
    administrationDetails: "Administered as an intravenous infusion over 10-30 minutes on specific days of a 28-day cycle. Typically given on days 1, 2, 8, 9, 15, 16. Requires premedication with dexamethasone. Hydration protocols are recommended.",
    storage: "Store unopened vials at 2-8°C. Reconstituted solution is stable for 24 hours refrigerated. Diluted solution for infusion is stable for 4 hours at room temperature.",
    mechanism: "Carfilzomib is a tetrapeptide epoxyketone that irreversibly inhibits the chymotrypsin-like activity of the 20S proteasome. Unlike the reversible inhibitor bortezomib, covalent binding provides sustained proteasome inhibition. This leads to accumulation of misfolded proteins, ER stress, and activation of the unfolded protein response, triggering myeloma cell apoptosis.",
    useCases: [],
    stacks: [],
    safetyNotes: "FDA-approved as Kyprolis. Significant risks include cardiac toxicity (heart failure, cardiac arrest), pulmonary hypertension, renal toxicity, and tumor lysis syndrome. Lower rates of peripheral neuropathy compared to bortezomib. Requires cardiac and renal monitoring.",
    researchBackground: "Developed by Onyx Pharmaceuticals (now Amgen). Approved by the FDA in 2012 for relapsed multiple myeloma. The ASPIRE and ENDEAVOR trials demonstrated significant improvements in progression-free survival. Based on the natural product epoxomicin structure.",
    relatedPeptideNames: ["Bortezomib"],
  },
  "Linaclotide": {
    primaryBenefit: "Constipation and IBS symptom relief",
    shortSummary: "A guanylate cyclase-C agonist for irritable bowel syndrome with constipation and chronic constipation.",
    benefits: "Linaclotide reduces abdominal pain and increases bowel movements in patients with IBS-C and chronic idiopathic constipation. It acts locally in the gut to enhance fluid secretion and reduce visceral hypersensitivity, addressing both the pain and motility components of IBS.",
    administrationMethod: "Oral",
    administrationDetails: "Taken as an oral capsule once daily on an empty stomach, at least 30 minutes before the first meal. Available in 72 mcg (CIC), 145 mcg (IBS-C), and 290 mcg (IBS-C) doses. Acts locally in the gut with minimal systemic absorption.",
    storage: "Store at room temperature 25°C. Keep in original container with desiccant. Protect from moisture. Do not subdivide or crush capsules.",
    mechanism: "Linaclotide is a 14-amino acid peptide with three disulfide bonds that binds to guanylate cyclase-C (GC-C) receptors on intestinal epithelial cells. This increases intracellular and extracellular cGMP, which activates CFTR chloride channels, promoting fluid secretion into the intestinal lumen. Extracellular cGMP also reduces pain-sensing visceral afferent nerve firing.",
    useCases: ["Gut Health"],
    stacks: [],
    safetyNotes: "FDA-approved as Linzess. Most common side effect is diarrhea, which may be severe and lead to discontinuation. Contraindicated in children under 2 years (fatal dehydration in young mice). Minimal systemic absorption reduces systemic side effect risk.",
    researchBackground: "Developed by Ironwood Pharmaceuticals and Forest Laboratories. Approved by the FDA in 2012. Based on the structure of guanylin/uroguanylin (endogenous GC-C ligands). Multiple Phase 3 trials demonstrated efficacy in both IBS-C and CIC with sustained benefit.",
    relatedPeptideNames: [],
  },
  "Teriparatide": {
    primaryBenefit: "Bone formation stimulation",
    shortSummary: "A recombinant PTH fragment that stimulates new bone formation for severe osteoporosis treatment.",
    benefits: "Teriparatide is the only osteoporosis treatment that stimulates new bone formation (anabolic) rather than simply preventing bone loss (anti-resorptive). It increases bone mineral density, improves bone microarchitecture, and reduces vertebral and non-vertebral fracture risk.",
    administrationMethod: "Subcutaneous Injection",
    administrationDetails: "Administered as a once-daily subcutaneous injection of 20 mcg using a multidose pen. Injected in the thigh or abdominal wall. Treatment duration is limited to 2 years due to theoretical osteosarcoma risk from preclinical studies.",
    storage: "Store pen in refrigerator at 2-8°C. Do not freeze. After first injection, pen can be used for up to 28 days when stored properly. Recap pen after each use.",
    mechanism: "Teriparatide is recombinant human PTH(1-34), the biologically active N-terminal fragment. Intermittent (once-daily) PTH exposure preferentially stimulates osteoblast activity over osteoclast activity, resulting in net bone formation. It activates PTH1R on osteoblasts, increasing Wnt signaling, IGF-1 production, and reducing sclerostin expression.",
    useCases: ["Bone Health"],
    stacks: [],
    safetyNotes: "FDA-approved as Forteo. Carries a boxed warning about osteosarcoma risk based on rat studies at high doses for extended durations. Treatment limited to 2 years. Common side effects include orthostatic hypotension, leg cramps, and transient hypercalcemia.",
    researchBackground: "Developed by Eli Lilly. Approved by the FDA in 2002. The pivotal Fracture Prevention Trial demonstrated 65% reduction in vertebral fractures and 53% reduction in non-vertebral fractures. First anabolic agent approved for osteoporosis. Changed the treatment paradigm from purely anti-resorptive approaches.",
    relatedPeptideNames: ["Abaloparatide"],
  },
  "Calcitonin-Salmon": {
    primaryBenefit: "Bone loss prevention and pain relief",
    shortSummary: "A salmon-derived calcitonin peptide that inhibits bone resorption and provides analgesic effects.",
    benefits: "Calcitonin-Salmon inhibits osteoclast-mediated bone resorption, helping to preserve bone density. It has a notable analgesic effect on bone pain, particularly useful in acute vertebral compression fractures and Paget's disease. It also helps regulate calcium levels in hypercalcemia.",
    administrationMethod: "Intranasal / Subcutaneous Injection",
    administrationDetails: "Available as nasal spray (Miacalcin/Fortical, 200 IU daily, alternating nostrils) or subcutaneous/intramuscular injection (100 IU daily or every other day). Nasal spray is the most common formulation for osteoporosis.",
    storage: "Unopened nasal spray bottles should be refrigerated at 2-8°C. Once opened, store at room temperature for up to 35 days. Injectable should be refrigerated.",
    mechanism: "Salmon calcitonin binds to calcitonin receptors (CTR) on osteoclasts with 40-50 times greater potency than human calcitonin. Receptor activation increases intracellular cAMP, causing osteoclast retraction from bone surfaces and reducing bone resorption. Analgesic effects are thought to involve endorphin release and direct CNS action.",
    useCases: ["Bone Health"],
    stacks: [],
    safetyNotes: "FDA-approved for decades. Common side effects include nasal irritation (spray), nausea, and flushing. An FDA advisory noted a possible small increase in cancer risk with long-term use, leading to recommendations for limited treatment duration. Generally used as second-line therapy.",
    researchBackground: "Salmon calcitonin was developed in the 1970s and has been used clinically for over 40 years. It was one of the first peptide therapies for osteoporosis. While largely superseded by bisphosphonates and newer agents, it remains valued for its bone pain analgesic effects.",
    relatedPeptideNames: ["Teriparatide", "Abaloparatide"],
  },
  "Setmelanotide": {
    primaryBenefit: "Treatment of rare genetic obesity",
    shortSummary: "An MC4R agonist approved for obesity caused by specific genetic deficiencies in the melanocortin pathway.",
    benefits: "Setmelanotide restores MC4R signaling in patients with genetic defects in the leptin-melanocortin pathway. It reduces hunger and body weight in patients with POMC, PCSK1, or LEPR deficiency obesity — conditions that do not respond to diet, exercise, or conventional weight-loss therapies.",
    administrationMethod: "Subcutaneous Injection",
    administrationDetails: "Administered as a once-daily subcutaneous injection. Dose is titrated based on response, starting at 2 mg daily with potential increase to 3 mg. Injected in the abdomen, thigh, or upper arm.",
    storage: "Store in refrigerator at 2-8°C. Protect from light. Do not freeze. Allow to reach room temperature before injection.",
    mechanism: "Setmelanotide is a cyclic peptide MC4R agonist that bypasses upstream defects in the melanocortin pathway. In patients with POMC, PCSK1, or LEPR deficiency, the melanocortin pathway that normally suppresses appetite is disrupted. Setmelanotide directly activates MC4R downstream of these defects, restoring satiety signaling.",
    useCases: ["Fat Loss", "Metabolic Health"],
    stacks: [],
    safetyNotes: "FDA-approved as Imcivree. Common side effects include injection site reactions, skin hyperpigmentation (due to MC1R activation), and spontaneous penile erections. Risk of depression and suicidal ideation requires monitoring. Only for genetically confirmed patients.",
    researchBackground: "Developed by Rhythm Pharmaceuticals. Approved by the FDA in 2020 for POMC, PCSK1, and LEPR deficiency obesity. Expanded approval in 2022 to include Bardet-Biedl syndrome. Represents precision medicine in obesity treatment, targeting the specific genetic cause.",
    relatedPeptideNames: ["PT-141", "Melanotan II", "Afamelanotide"],
  },
  "Abaloparatide": {
    primaryBenefit: "Bone formation for osteoporosis",
    shortSummary: "A PTHrP analog that stimulates bone formation with potentially less hypercalcemia risk than teriparatide.",
    benefits: "Abaloparatide stimulates new bone formation to reduce fracture risk in postmenopausal osteoporosis. It increases bone mineral density at the spine, hip, and femoral neck. Compared to teriparatide, it may cause less hypercalcemia while providing similar fracture risk reduction.",
    administrationMethod: "Subcutaneous Injection",
    administrationDetails: "Administered as a once-daily subcutaneous injection of 80 mcg using a multidose pen. Injected in the periumbilical area of the abdomen. Treatment duration is limited to 2 years.",
    storage: "Store pen in refrigerator at 2-8°C before first use. After first use, store at room temperature up to 25°C for up to 30 days. Do not freeze.",
    mechanism: "Abaloparatide is a synthetic analog of PTHrP(1-34) that preferentially activates the RG conformation of PTH1R. This selectivity produces a more transient signaling response compared to teriparatide, favoring anabolic bone effects over resorptive effects. It increases osteoblast number and activity while producing smaller and shorter calcium elevations.",
    useCases: ["Bone Health"],
    stacks: [],
    safetyNotes: "FDA-approved as Tymlos. Same boxed warning about osteosarcoma risk as teriparatide based on preclinical studies. Lower incidence of hypercalcemia versus teriparatide. Common side effects include dizziness, nausea, and headache.",
    researchBackground: "Developed by Radius Health. Approved by the FDA in 2017. The ACTIVE trial demonstrated 86% reduction in vertebral fractures and 43% reduction in non-vertebral fractures. Provides an alternative anabolic approach to osteoporosis with a differentiated mechanism from teriparatide.",
    relatedPeptideNames: ["Teriparatide", "Calcitonin-Salmon"],
  },
  "Difelikefalin": {
    primaryBenefit: "Itch relief for kidney disease patients",
    shortSummary: "A peripheral kappa opioid receptor agonist for treatment of chronic itch in dialysis patients.",
    benefits: "Difelikefalin provides significant relief from chronic kidney disease-associated pruritus (CKD-aP), a debilitating condition affecting up to 70% of hemodialysis patients. It reduces itch intensity and improves quality of life and sleep without central nervous system side effects typical of traditional opioids.",
    administrationMethod: "IV Infusion",
    administrationDetails: "Administered as an intravenous bolus injection of 0.5 mcg/kg into the venous line of the dialysis circuit at the end of each hemodialysis session (3 times per week). An oral formulation is under development.",
    storage: "Store vials at room temperature 20-25°C. Protect from light. Single-use vials — discard unused portion.",
    mechanism: "Difelikefalin is a synthetic D-amino acid tetrapeptide that selectively activates peripheral kappa opioid receptors (KOR). Unlike centrally acting opioids, it does not cross the blood-brain barrier, avoiding dysphoria, sedation, and addiction. Peripheral KOR activation on immune cells and sensory neurons modulates itch signaling through anti-inflammatory and anti-pruritic pathways.",
    useCases: [],
    stacks: [],
    safetyNotes: "FDA-approved as Korsuva. Common side effects include diarrhea, dizziness, and gait disturbance. Does not cause typical opioid side effects (euphoria, respiratory depression, dependence) due to lack of CNS penetration.",
    researchBackground: "Developed by Cara Therapeutics. Approved by the FDA in 2021 for CKD-associated pruritus in hemodialysis patients. The KALM-1 and KALM-2 Phase 3 trials demonstrated significant itch reduction versus placebo. Represents a novel approach to treating itch through peripheral opioid mechanisms.",
    relatedPeptideNames: ["Ziconotide"],
  },
};

// ═══════════════════════════════════════════════════════════════════════
// SIDE EFFECTS & SOURCES — Supplementary data merged at build time
// ═══════════════════════════════════════════════════════════════════════

export const PEPTIDE_SUPPLEMENTS: Record<string, { sideEffects: string; sources: PeptideSourceRef[] }> = {
  "Semaglutide": {
    sideEffects: "Common side effects include nausea (20-44%), vomiting, diarrhea, constipation, and abdominal pain, particularly during dose escalation. Injection site reactions, headache, and fatigue have been reported. Rare but serious risks include pancreatitis, gallbladder events, and acute kidney injury. Carries a boxed warning for thyroid C-cell tumors observed in rodent studies.",
    sources: [
      { title: "STEP 1 Trial — Semaglutide for Weight Management (NEJM, 2021)", url: "https://pubmed.ncbi.nlm.nih.gov/33567185/" },
      { title: "SELECT Cardiovascular Outcomes Trial (NEJM, 2023)", url: "https://pubmed.ncbi.nlm.nih.gov/37952131/" },
      { title: "FDA Prescribing Information — Ozempic (DailyMed)", url: "https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=ozempic" },
      { title: "Semaglutide Clinical Trials — ClinicalTrials.gov", url: "https://clinicaltrials.gov/search?term=semaglutide" },
    ],
  },
  "Tirzepatide": {
    sideEffects: "Common side effects include nausea (12-33%), diarrhea, vomiting, constipation, decreased appetite, and injection site reactions. Gastrointestinal effects are generally most pronounced during dose escalation. Rare risks include pancreatitis and gallbladder events. Carries the same thyroid C-cell tumor boxed warning as GLP-1 receptor agonists.",
    sources: [
      { title: "SURMOUNT-1 Trial — Tirzepatide for Obesity (NEJM, 2022)", url: "https://pubmed.ncbi.nlm.nih.gov/35658024/" },
      { title: "FDA Prescribing Information — Mounjaro (DailyMed)", url: "https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=mounjaro" },
      { title: "Tirzepatide Clinical Trials — ClinicalTrials.gov", url: "https://clinicaltrials.gov/search?term=tirzepatide" },
    ],
  },
  "BPC-157": {
    sideEffects: "Human clinical trial data is very limited. Animal studies have reported minimal adverse effects at therapeutic doses. Anecdotal reports from research contexts include nausea, dizziness, and headache. No large-scale human safety trials have been published, so the full side effect profile remains poorly characterized.",
    sources: [
      { title: "BPC 157 Pharmacological Effects — Review (Current Pharmaceutical Design)", url: "https://pubmed.ncbi.nlm.nih.gov/?term=BPC-157+stable+gastric+pentadecapeptide+review" },
      { title: "BPC 157 Tissue Healing Research — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=BPC-157+healing" },
      { title: "BPC-157 Studies — ClinicalTrials.gov", url: "https://clinicaltrials.gov/search?term=BPC-157" },
    ],
  },
  "TB-500": {
    sideEffects: "Limited human clinical data is available. Anecdotal reports from research use include headache, lethargy, nausea, and localized discomfort at injection sites. No large-scale human safety trials have been published. The side effect profile is not well established in peer-reviewed literature.",
    sources: [
      { title: "Thymosin Beta-4 in Tissue Repair — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=thymosin+beta-4+tissue+repair" },
      { title: "Thymosin Beta-4 Wound Healing Research — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=thymosin+beta-4+wound+healing" },
    ],
  },
  "Thymosin Beta-4": {
    sideEffects: "In limited clinical studies, thymosin beta-4 has been generally well-tolerated. Reported side effects include injection site irritation and mild discomfort. Phase 2 trials in wound healing and dry eye have not identified major safety concerns, though data remains limited.",
    sources: [
      { title: "Thymosin Beta-4 Clinical Applications — Review", url: "https://pubmed.ncbi.nlm.nih.gov/?term=thymosin+beta-4+clinical+trial" },
      { title: "Thymosin Beta-4 in Corneal Wound Healing — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=thymosin+beta-4+corneal+healing" },
    ],
  },
  "Thymosin Alpha-1": {
    sideEffects: "Generally well-tolerated in clinical use. Reported side effects include injection site reactions (pain, erythema), fatigue, and rash. Rare reports of flu-like symptoms. Extensive clinical use in Asia and Europe for hepatitis and immune support has shown a favorable safety profile.",
    sources: [
      { title: "Thymosin Alpha-1 in Hepatitis B — Clinical Review", url: "https://pubmed.ncbi.nlm.nih.gov/?term=thymosin+alpha-1+hepatitis+clinical" },
      { title: "Thymosin Alpha-1 Immune Modulation — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=thymosin+alpha-1+immune+modulation" },
      { title: "Thymosin Alpha-1 Safety Profile — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=thymosin+alpha-1+safety" },
    ],
  },
  "CJC-1295": {
    sideEffects: "Reported effects in research settings include flushing, warmth, headache, dizziness, water retention, and injection site reactions. Transient numbness or tingling has been noted. No large-scale controlled safety trials have been published. As a GHRH analog, potential risks include those associated with elevated growth hormone levels.",
    sources: [
      { title: "CJC-1295 Pharmacokinetics Study — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=CJC-1295+growth+hormone" },
      { title: "GHRH Analogs in Growth Hormone Research — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=GHRH+analog+growth+hormone+releasing" },
    ],
  },
  "Ipamorelin": {
    sideEffects: "Reported effects in research settings include headache, flushing, dizziness, nausea, and injection site reactions. Unlike other growth hormone secretagogues, ipamorelin shows minimal effect on cortisol and prolactin at therapeutic doses. No large-scale human safety trials have been published.",
    sources: [
      { title: "Ipamorelin Selectivity as GH Secretagogue — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=ipamorelin+growth+hormone+secretagogue" },
      { title: "Ipamorelin Clinical Studies — ClinicalTrials.gov", url: "https://clinicaltrials.gov/search?term=ipamorelin" },
    ],
  },
  "AOD-9604": {
    sideEffects: "Limited human data from phase 2 trials. Reported side effects include injection site reactions and headache. The peptide was generally well-tolerated in available clinical studies, though pivotal trials for obesity were not completed. Long-term safety data is not available.",
    sources: [
      { title: "AOD-9604 Fat Metabolism Research — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=AOD-9604+obesity+fat" },
      { title: "hGH Fragment 177-191 Research — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=hGH+fragment+177-191" },
    ],
  },
  "GHK-Cu": {
    sideEffects: "Topical application is generally well-tolerated with rare reports of skin irritation or redness. Injectable forms have very limited safety data. As a naturally occurring peptide-copper complex found in human plasma, GHK-Cu has not shown significant toxicity in available studies.",
    sources: [
      { title: "GHK-Cu Skin Remodeling and Anti-Aging — Review", url: "https://pubmed.ncbi.nlm.nih.gov/?term=GHK-Cu+copper+peptide+skin" },
      { title: "GHK Peptide Biological Activity — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=GHK+peptide+wound+healing+review" },
    ],
  },
  "PT-141": {
    sideEffects: "Common side effects include nausea (40%), flushing (20%), headache, and injection site reactions. Transient increases in blood pressure have been observed. Skin hyperpigmentation may occur with repeated use due to melanocortin receptor activation. Contraindicated in patients with uncontrolled hypertension.",
    sources: [
      { title: "FDA Prescribing Information — Vyleesi (DailyMed)", url: "https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=vyleesi" },
      { title: "Bremelanotide Clinical Trials — ClinicalTrials.gov", url: "https://clinicaltrials.gov/search?term=bremelanotide" },
      { title: "Bremelanotide for HSDD — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=bremelanotide+hypoactive+sexual+desire" },
    ],
  },
  "DSIP": {
    sideEffects: "Very limited human clinical data. Anecdotal reports include drowsiness (expected given its sleep-promoting effects) and headache. The peptide has a very short half-life, which may limit systemic side effects. No large-scale safety studies have been conducted.",
    sources: [
      { title: "Delta Sleep-Inducing Peptide Research — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=delta+sleep+inducing+peptide" },
      { title: "DSIP Neuromodulation — Review", url: "https://pubmed.ncbi.nlm.nih.gov/?term=DSIP+sleep+peptide+review" },
    ],
  },
  "Melanotan II": {
    sideEffects: "Common side effects include nausea (especially during initial use), facial flushing, fatigue, and injection site reactions. A significant safety concern is the darkening of existing moles and nevi, which complicates skin cancer surveillance. Other reported effects include appetite suppression and spontaneous penile erections.",
    sources: [
      { title: "Melanotan II Safety Concerns — Review", url: "https://pubmed.ncbi.nlm.nih.gov/?term=melanotan+II+safety+adverse" },
      { title: "Melanocortin Agonists and Skin Effects — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=melanotan+skin+pigmentation+safety" },
    ],
  },
  "MOTS-c": {
    sideEffects: "Very limited human clinical data is available. As an endogenous mitochondrial-derived peptide, it is expected to have a favorable safety profile, though this has not been confirmed in controlled trials. No well-documented side effects from published clinical studies exist.",
    sources: [
      { title: "MOTS-c Metabolic Regulation — Original Discovery", url: "https://pubmed.ncbi.nlm.nih.gov/?term=MOTS-c+mitochondrial+derived+peptide+Lee" },
      { title: "MOTS-c Exercise and Metabolism — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=MOTS-c+metabolism+insulin" },
    ],
  },
  "Kisspeptin": {
    sideEffects: "In clinical studies, kisspeptin has been generally well-tolerated. Reported side effects include injection site reactions, hot flashes, and headache. As it stimulates GnRH release, hormonal fluctuations (LH, FSH) are expected pharmacological effects rather than adverse events.",
    sources: [
      { title: "Kisspeptin in Reproductive Medicine — Review", url: "https://pubmed.ncbi.nlm.nih.gov/?term=kisspeptin+reproductive+clinical" },
      { title: "Kisspeptin Clinical Trials — ClinicalTrials.gov", url: "https://clinicaltrials.gov/search?term=kisspeptin" },
    ],
  },
  "Sermorelin": {
    sideEffects: "Reported side effects include injection site reactions (pain, swelling, redness), facial flushing, headache, dizziness, and hyperactivity. Transient effects on cortisol and prolactin are generally minimal. The drug was FDA-approved (Geref) with an established safety profile, though it has since been discontinued.",
    sources: [
      { title: "Sermorelin Growth Hormone Research — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=sermorelin+growth+hormone+deficiency" },
      { title: "GHRH Analogs Clinical Use — Review", url: "https://pubmed.ncbi.nlm.nih.gov/?term=sermorelin+GHRH+analog+clinical" },
    ],
  },
  "Tesamorelin": {
    sideEffects: "Common side effects include injection site reactions (erythema, pruritus, pain), arthralgia, peripheral edema, and myalgia. May cause fluid retention and joint pain due to growth hormone elevation. Contraindicated in pregnancy due to potential teratogenic effects. May affect glucose metabolism.",
    sources: [
      { title: "FDA Prescribing Information — Egrifta (DailyMed)", url: "https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=egrifta" },
      { title: "Tesamorelin for HIV Lipodystrophy — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=tesamorelin+HIV+lipodystrophy" },
      { title: "Tesamorelin Clinical Trials — ClinicalTrials.gov", url: "https://clinicaltrials.gov/search?term=tesamorelin" },
    ],
  },
  "Epitalon": {
    sideEffects: "Very limited human clinical data. Published studies from Russian research groups report minimal adverse effects, though these studies are limited in scope and sample size. No well-documented side effects from large controlled trials exist. Long-term safety has not been established.",
    sources: [
      { title: "Epithalamin and Telomerase Research — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=epitalon+epithalamin+telomerase" },
      { title: "Pineal Peptides and Aging — Review", url: "https://pubmed.ncbi.nlm.nih.gov/?term=epithalamin+pineal+peptide+aging" },
    ],
  },
  "LL-37": {
    sideEffects: "Topical application may cause localized skin irritation or redness. Injectable forms have very limited safety data in humans. At high concentrations, cathelicidins can potentially be cytotoxic to host cells. The peptide's role in inflammatory conditions means immune activation is a theoretical concern.",
    sources: [
      { title: "LL-37 Cathelicidin Antimicrobial Functions — Review", url: "https://pubmed.ncbi.nlm.nih.gov/?term=LL-37+cathelicidin+antimicrobial+review" },
      { title: "Human Cathelicidin in Innate Immunity — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=cathelicidin+LL-37+innate+immunity" },
    ],
  },
  "Selank": {
    sideEffects: "Generally well-tolerated in clinical use. Reported side effects include nasal irritation (with intranasal administration), fatigue, and mild drowsiness. No significant adverse effects have been reported in published clinical studies. Has been used clinically in Russia since its approval.",
    sources: [
      { title: "Selank Anxiolytic Properties — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=selank+anxiolytic+peptide" },
      { title: "Selank Pharmacology Review — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=selank+tuftsin+analog+pharmacology" },
    ],
  },
  "Semax": {
    sideEffects: "Generally well-tolerated. Reported side effects include nasal irritation (intranasal route), bitter taste, and rare headache. No significant adverse effects have been reported in published clinical studies. Has been used clinically in Russia for neuroprotection and cognitive enhancement.",
    sources: [
      { title: "Semax Neuroprotective Effects — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=semax+neuroprotective+ACTH+analog" },
      { title: "Semax Clinical Applications — Review", url: "https://pubmed.ncbi.nlm.nih.gov/?term=semax+cognitive+enhancement+clinical" },
    ],
  },
  "Gonadorelin": {
    sideEffects: "Common side effects include headache, nausea, abdominal discomfort, flushing, and injection site reactions. In women, ovarian hyperstimulation syndrome is a potential risk when used for fertility treatment. Multiple pregnancy is possible with fertility applications. Light-headedness and dizziness have been reported.",
    sources: [
      { title: "FDA Prescribing Information — Gonadorelin (DailyMed)", url: "https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=gonadorelin" },
      { title: "GnRH in Reproductive Medicine — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=gonadorelin+GnRH+clinical+use" },
    ],
  },
  "Liraglutide": {
    sideEffects: "Common side effects include nausea (28-39%), diarrhea, vomiting, constipation, headache, and injection site reactions. Gastrointestinal effects typically diminish over time. Rare but serious risks include pancreatitis, gallbladder disease, and acute kidney injury. Carries the thyroid C-cell tumor boxed warning.",
    sources: [
      { title: "SCALE Obesity Trial — Liraglutide 3.0 mg (NEJM, 2015)", url: "https://pubmed.ncbi.nlm.nih.gov/25673552/" },
      { title: "FDA Prescribing Information — Victoza (DailyMed)", url: "https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=victoza" },
      { title: "Liraglutide Clinical Trials — ClinicalTrials.gov", url: "https://clinicaltrials.gov/search?term=liraglutide" },
    ],
  },
  "Octreotide": {
    sideEffects: "Common side effects include gastrointestinal effects (diarrhea, nausea, abdominal pain), injection site pain, and headache. Gallstones develop in 15-30% of patients with long-term use. May cause hyperglycemia or hypoglycemia due to effects on insulin and glucagon. Fatigue and dizziness have been reported.",
    sources: [
      { title: "FDA Prescribing Information — Sandostatin (DailyMed)", url: "https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=sandostatin" },
      { title: "Octreotide in Neuroendocrine Tumors — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=octreotide+neuroendocrine+tumor+clinical" },
    ],
  },
  "Exenatide": {
    sideEffects: "Common side effects include nausea (44%), vomiting, diarrhea, headache, and injection site reactions. Nausea is most common during initiation and generally decreases over time. Rare risks include pancreatitis and thyroid C-cell tumors (boxed warning). Anti-exenatide antibodies may develop in some patients.",
    sources: [
      { title: "FDA Prescribing Information — Byetta (DailyMed)", url: "https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=byetta" },
      { title: "Exenatide Clinical Development — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=exenatide+clinical+trial+type+2+diabetes" },
    ],
  },
  "Leuprolide": {
    sideEffects: "Common side effects include hot flashes, injection site reactions, decreased libido, erectile dysfunction, and mood changes. Long-term use may cause bone density loss. An initial testosterone flare occurs in the first 1-2 weeks of treatment in prostate cancer, which can temporarily worsen symptoms. Fatigue and weight gain are frequently reported.",
    sources: [
      { title: "FDA Prescribing Information — Lupron (DailyMed)", url: "https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=lupron" },
      { title: "Leuprolide in Prostate Cancer — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=leuprolide+prostate+cancer+clinical" },
    ],
  },
  "Dulaglutide": {
    sideEffects: "Common side effects include nausea (12-21%), diarrhea, vomiting, decreased appetite, abdominal pain, and fatigue. Injection site reactions occur infrequently. Rare risks include pancreatitis and gallbladder events. Carries the thyroid C-cell tumor boxed warning common to GLP-1 receptor agonists.",
    sources: [
      { title: "FDA Prescribing Information — Trulicity (DailyMed)", url: "https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=trulicity" },
      { title: "REWIND Cardiovascular Outcomes Trial — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=dulaglutide+REWIND+cardiovascular" },
    ],
  },
  "Desmopressin": {
    sideEffects: "Common side effects include headache, nausea, nasal congestion (intranasal route), and abdominal cramps. The most significant risk is hyponatremia (low sodium), particularly in elderly patients or those with excessive fluid intake. Water intoxication can occur if fluid intake is not restricted. Facial flushing has been reported.",
    sources: [
      { title: "FDA Prescribing Information — DDAVP (DailyMed)", url: "https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=desmopressin" },
      { title: "Desmopressin Clinical Use — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=desmopressin+clinical+safety+hyponatremia" },
    ],
  },
  "Ziconotide": {
    sideEffects: "Common side effects include dizziness, nausea, confusion, headache, somnolence, and nystagmus. Psychiatric adverse effects (depression, cognitive impairment, hallucinations) are significant concerns. Requires careful dose titration to minimize neurological side effects. Must be delivered intrathecally, which carries procedure-related risks including meningitis.",
    sources: [
      { title: "FDA Prescribing Information — Prialt (DailyMed)", url: "https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=prialt" },
      { title: "Ziconotide for Chronic Pain — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=ziconotide+intrathecal+chronic+pain" },
    ],
  },
  "Carfilzomib": {
    sideEffects: "Common side effects include fatigue, anemia, nausea, thrombocytopenia, dyspnea, diarrhea, and fever. Serious cardiovascular events (heart failure, cardiac arrest, myocardial ischemia) have been reported. Infusion reactions may occur. Hepatotoxicity and tumor lysis syndrome are additional risks. Requires regular monitoring of blood counts and cardiac function.",
    sources: [
      { title: "FDA Prescribing Information — Kyprolis (DailyMed)", url: "https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=kyprolis" },
      { title: "ASPIRE Trial — Carfilzomib in Myeloma (NEJM)", url: "https://pubmed.ncbi.nlm.nih.gov/?term=carfilzomib+ASPIRE+multiple+myeloma" },
    ],
  },
  "Linaclotide": {
    sideEffects: "Diarrhea is the most common side effect (16-20%) and the most frequent reason for discontinuation. Other reported effects include abdominal pain, flatulence, and abdominal distension. Severe diarrhea may require dose reduction or discontinuation. Contraindicated in pediatric patients under 2 years due to risk of serious dehydration.",
    sources: [
      { title: "FDA Prescribing Information — Linzess (DailyMed)", url: "https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=linzess" },
      { title: "Linaclotide in IBS-C — Clinical Trials", url: "https://pubmed.ncbi.nlm.nih.gov/?term=linaclotide+irritable+bowel+constipation+trial" },
    ],
  },
  "Teriparatide": {
    sideEffects: "Common side effects include orthostatic hypotension, leg cramps, nausea, dizziness, and injection site reactions. Transient hypercalcemia may occur after injection. Carries a boxed warning for osteosarcoma based on findings in rat studies at high doses and long durations. Treatment duration is limited to 2 years.",
    sources: [
      { title: "FDA Prescribing Information — Forteo (DailyMed)", url: "https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=forteo" },
      { title: "Teriparatide in Osteoporosis — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=teriparatide+osteoporosis+clinical+trial" },
    ],
  },
  "Calcitonin-Salmon": {
    sideEffects: "Nasal spray: rhinitis, nasal irritation, epistaxis. Injectable: nausea, facial flushing, injection site reactions. Rare allergic reactions may occur. The FDA issued a safety advisory regarding a possible association between long-term calcitonin use and increased cancer risk, leading to restricted use in some markets.",
    sources: [
      { title: "FDA Prescribing Information — Miacalcin (DailyMed)", url: "https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=miacalcin" },
      { title: "Calcitonin Safety and Cancer Risk — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=calcitonin+salmon+safety+cancer+risk" },
    ],
  },
  "Setmelanotide": {
    sideEffects: "Common side effects include injection site reactions, skin hyperpigmentation, nausea, diarrhea, and abdominal pain. Sexual adverse reactions (spontaneous penile erections, sexual adverse events) have been reported due to melanocortin receptor activation. Disturbances in skin pigmentation are expected given the mechanism of action.",
    sources: [
      { title: "FDA Prescribing Information — Imcivree (DailyMed)", url: "https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=imcivree" },
      { title: "Setmelanotide for Genetic Obesity — PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/?term=setmelanotide+POMC+deficiency+obesity" },
    ],
  },
  "Abaloparatide": {
    sideEffects: "Common side effects include injection site reactions, hypercalciuria, dizziness, nausea, headache, palpitations, fatigue, and orthostatic hypotension. Carries a boxed warning for osteosarcoma based on rat studies, similar to teriparatide. Treatment duration is limited to 2 years. Transient hypercalcemia may occur.",
    sources: [
      { title: "FDA Prescribing Information — Tymlos (DailyMed)", url: "https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=tymlos" },
      { title: "ACTIVE Trial — Abaloparatide in Osteoporosis", url: "https://pubmed.ncbi.nlm.nih.gov/?term=abaloparatide+ACTIVE+osteoporosis+trial" },
    ],
  },
  "Difelikefalin": {
    sideEffects: "Common side effects include diarrhea, dizziness, nausea, somnolence, and vomiting. Some patients experience gait disturbances. Unlike centrally-acting opioids, difelikefalin does not cause euphoria, respiratory depression, or physical dependence due to its peripheral mechanism. QTc prolongation has been reported at supratherapeutic doses.",
    sources: [
      { title: "FDA Prescribing Information — Korsuva (DailyMed)", url: "https://dailymed.nlm.nih.gov/dailymed/search.cfm?labeltype=all&query=korsuva" },
      { title: "KALM-1 Trial — Difelikefalin for CKD Pruritus", url: "https://pubmed.ncbi.nlm.nih.gov/?term=difelikefalin+KALM+pruritus+hemodialysis" },
    ],
  },
};
